language: php

php:
  - 7.1

cache:
  directories:
    - vendor

sudo: required

services:
  - docker

before_install:
  - ./install.sh

script:
  - docker exec -it phalcon-cassandra vendor/bin/codecept run unit

notifications:
    email:
        recipients:
            - smorard@idobs.net
        on_success: change
        on_failure: always