language: php

# TODO To use `sudo: false` you have to use `precise` until this issue is fixed:
# https://github.com/travis-ci/travis-ci/issues/5837
dist: precise
sudo: false
# dist: trusty
# sudo: required

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    # Use ZEPHIR_PARSER_VERSION here
    - $HOME/zephir-parser-v1.0.3
    - $HOME/beanstalk
    - $HOME/.ccache
    - $HOME/.composer/cache
    - $HOME/pear

env:
  global:
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"
    - ZEPHIR_PARSER_VERSION="v1.0.3"
    # Uncomment for debug
    #- ZEND_DONT_UNLOAD_MODULES=1

before_install:
  - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1)"
  - bash tests/_ci/pear_setup.sh
  - bash tests/_ci/setup_dbs.sh

install:
  - travis_retry composer install --quiet --no-interaction --no-ansi --no-progress --optimize-autoloader --dev --prefer-dist --no-suggest --ignore-platform-reqs
  - bash tests/_ci/install_prereqs_$PHP_MAJOR.sh
  - bash tests/_ci/install_zephir_parser.sh
  - bash tests/_ci/install_zephir.sh
  - zephir generate
  - (export PRE_PHP_INCLUDES=`php-config --includes`; cd ext/; for file in `find kernel -name "*.h"`; do $CC "$file" -I. $PRE_PHP_INCLUDES -o "$file.ghc"; done)
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; $(phpenv which phpize) &> /dev/null && ./configure --silent --with-php-config=$(phpenv which php-config) --enable-phalcon &> /dev/null && make --silent -j"$(getconf _NPROCESSORS_ONLN)" &> /dev/null && make --silent install)
  # Uncomment for debug
  # - (cd ext; export CFLAGS="-g3 -O0 -std=gnu90 -Wall"; $(phpenv which phpize) &> /dev/null && ./configure --silent --with-php-config=$(phpenv which php-config) --enable-phalcon &> /dev/null && make --silent -j"$(getconf _NPROCESSORS_ONLN)" &> /dev/null && make --silent install)
  - phpenv config-add tests/_ci/phalcon.ini
  - phpenv config-add tests/_ci/ci.ini

before_script:
  # Uncomment for debug
  # - ulimit -c unlimited -S || true
  # - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null

script:
  - php -r "echo \Phalcon\Version::get();"
#  - vendor/bin/phpcs
#  - vendor/bin/phpunit --bootstrap tests/_ci/phpunit.php --debug unit-tests/
#  - vendor/bin/codecept build
#  - vendor/bin/codecept run -v -n tests/integration/
#  - vendor/bin/codecept run -v -n tests/unit/
  # Legacy tests
  - phpenv config-rm xdebug.ini
  - if [[ "$PHP_MAJOR" == 5 ]]; then vendor/bin/codecept run -v -n tests/unit5x/; fi;

# Uncomment for debug
# after_failure:
#  - bash tests/_ci/after_failure.sh

notifications:
    email:
        recipients:
            - smorard@idobs.net
        on_success: change
        on_failure: always

addons:
    apt:
        packages:
            - re2c
