language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - bin/install-phalcon.sh 3.0.x

script:
  - php -r "echo \Phalcon\Version::get();"

notifications:
  email: false