language: php

php:
  - 7.1

cache:
  directories:
    - vendor

sudo: required

services:
  - docker

before_install:
  - ./install.sh

script:
  - docker exec php-phalcon-cassandra vendor/bin/codecept run unit PhalconCest
  - docker exec php-phalcon-cassandra vendor/bin/codecept run unit CassandraCest
  - docker exec php-phalcon-cassandra vendor/bin/codecept run unit CassandraAsyncCest

notifications:
    email:
        recipients:
            - smorard@idobs.net
        on_success: change
        on_failure: always