language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

sudo: required

services:
  - docker

before_install:
  - composer install --prefer-source --no-interaction

script:
  - php -r "echo 'ok';"

notifications:
    email:
        recipients:
            - smorard@idobs.net
        on_success: change
        on_failure: always